package com.trainings.jdbc.frontend;

import java.sql.Connection;
import java.util.List;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import com.trainings.jdbc.queryhandler.QueryHandler;
import com.trainings.jdbc.tables.Film;


import java.sql.Connection;

/**
 *
 * @author Home Laptop
 */
public class HomePage extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    private Connection con = null;
    public HomePage(Connection connection) {
        con = connection;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        result = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("My IMDB");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButton1.setActionCommand("Search");
        jButton1.setLabel("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        result.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title", "Relase", "Duration", "Popularity Score", "Genre", "Actor", "Actress", "Director", "Awards", "Image"
            }
        ));
        jScrollPane1.setViewportView(result);

        jButton2.setText("Top 25 ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 786, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(77, 77, 77))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(256, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        
    	cleanResultTable();

    	List<Film> results = QueryHandler.getDataFromTable("film", "AND title like '%", jTextField1.getText()+"%'", con);
    	if(results.size() == 0){
    		//result.disable();
    	}
    	for(int i=0; i<results.size(); i++){
    		Object[] row = { results.get(i).getTitle(), results.get(i).getYearOfRelease(), results.get(i).getLength(), results.get(i).getPopularity(),results.get(i).getGenre(),results.get(i).getActor(),results.get(i).getActress(),results.get(i).getDirector(),results.get(i).getAwards(),results.get(i).getImage() };
    		DefaultTableModel model = (DefaultTableModel) result.getModel();
    		model.addRow(row);
    	}
    }                                        

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                         
    	cleanResultTable();
    	List<Film> results = QueryHandler.getDataFromTable("film", "order by popularity desc limit 25", "", con);
    	if(results.size() == 0){
    		//result.disable();
    	}
    	for(int i=0; i<results.size(); i++){
    		Object[] row = { results.get(i).getTitle(), results.get(i).getYearOfRelease(), results.get(i).getLength(), results.get(i).getPopularity(),results.get(i).getGenre(),results.get(i).getActor(),results.get(i).getActress(),results.get(i).getDirector(),results.get(i).getAwards(),results.get(i).getImage() };
    		DefaultTableModel model = (DefaultTableModel) result.getModel();
    		model.addRow(row);
    	}
    	
    }                                        

    private void cleanResultTable(){
    	DefaultTableModel model = (DefaultTableModel)result.getModel(); 
    	int rows = model.getRowCount(); 
    	for(int i = rows - 1; i >=0; i--)
    	   model.removeRow(i); 
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTable result;
    // End of variables declaration                   
}